name: CI Pipeline

on:
  push:
    branches:
      - main # Production branch
      - stage # Pre-production branch
      - dev # Development branch
  pull_request:
    branches:
      - main
      - stage
      - dev

jobs:
  frontend:
    name: Frontend Build & Test
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: frontend

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: npm install

      - name: Lint code
        run: npm run lint

      - name: Run tests
        run: npm run test

  backend:
    name: Backend Build & Test
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: npm install

      - name: Lint code
        run: npm run lint

      - name: Run tests
        run: npm run test

  deployment-check:
    name: Deployment Readiness Check
    runs-on: ubuntu-latest
    needs: [frontend, backend]
    if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/stage'

    steps:
      - name: Check deployment readiness
        run: echo "✅ All tests passed. Ready for deployment!"
